### ISSUE TITLE
Double Height issue in Safari and Chrome

### ISSUE THREAD

**Issue by delflux** [PaulSpr/jQuery-Equal-Height-Columns#3]
Hello. I'm have an issue with Chrome and Safari. It doubles the div height on each resize (when sized up from mobile responsive to desktop layout). Works fine in IE and Firefox.

Test Fiddle: http://jsfiddle.net/bF5MR/
Site here: http://test.modernhometours.com/about-us/

**Comment by delflux** [comment]
I've figured out when I'm in mobile responsive layout and I hit the maximize button on the browser window, the height calculation is off.

**Comment by PaulSpr** [comment]
This is a fun one. It seems to be a problem caused by Bootstrap. When I resize to a smaller viewport it shifts to a very narrow column for a fraction of a second, the height jQuery then seems top calculate is very high. Somehow it seems to hold that value when the columns get there actual value.

I swapped all the CSS with the following simple code and I can't get the bug to appear. So it must be something in the Bootstrap CSS causing this.

``` css
@media screen and (min-width: 480px) {       
    .content{
        overflow: hidden;
    }
    .main{
        float: left;
        width: 61%;
        padding: 0 2%;
    }
    .sidebar{
        float: left;
        width: 31%;
        padding: 0 2%;
    }
}
```

**Comment by PaulSpr** [comment]
I investigated further and now know the reason Bootstrap is messing up the height calculations. They transition every change to every div on the page (doesn't seem very efficient) for .2s. jQuery probably calculates the height at the beginning of the transition which is the point that the transition is in a weird state causing the narrow column.

I think I might be able to check if an element has a transition and then delay the calculations for as long the transition would take. This might cause some funky behavior when resizing, but we'll have to see.

For now this will fix your problem. Just add these lines after the Bootstrap CSS and everything will work fine.

``` css
div {
-webkit-transition: all 0s ease-out;
-moz-transition: all 0s ease-out;
-o-transition: all 0s ease-out;
transition: all 0s ease-out;
}
```
